# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'e7ce1367-0390-4508-83db-57c4fff2e7bb'
  imageRepository: 'venkatmavenrepo'
  containerRegistry: 'javaapplication.azurecr.io'


  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
  
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'azureResourceManager'
        azureSubscriptionConnection: 'Venkat-subscription(2)(1bbb4b4e-65ec-4a38-a43c-b60ac9808b60)'
        azureResourceGroup: 'frontend-pipeline'
        kubernetesCluster: 'java-application'
        useClusterAdmin: true
        namespace: 'app'
        dockerfilePath: 'Dockerfile'
        tag: '$(Build.BuildId)'