apiVersion : apps/v1
kind: Deployment
metadata:
  name: venkatmavenrepo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: venkatmavenrepo
  template:
    metadata:
      labels:
        app: venkatmavenrepo 
    spec:
      containers:
        - name: venkatmavenrepo 
          image: mavenbackend.azurecr.io/venkatmavenrepo:29
          ports:
          - containerPort: 8080
